# Generated by Django 5.2.12 on 2026-08-30 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0008_apartment_acquisition_year_and_more'),
        ('services', '0004_wifipayment_checkout_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('bill_type', models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('WIFI', 'Wi-Fi'), ('RECEIPT', 'Receipt'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('TEST', 'Test'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], db_index=True, default='QUEUED', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_messages', to=settings.AUTH_USER_MODEL)),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='rentals.rent')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='rentals.tenant')),
                ('water_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='services.waterbill')),
                ('wifi_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='services.wificustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
