# Generated by Django 5.2.12 on 2026-05-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_mpesacallbacklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.rent'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
