# Generated by Django 5.2.12 on 2026-05-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_rent_alter_payment_checkout_request_id'),
        ('rentals', '0003_rent_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rental_rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rentals.rent'),
        ),
    ]
