# Generated by Django 5.2.12 on 2026-07-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=250)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enterprise/company_logos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('is_head_office', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='enterprise.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='enterprise.currency'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='enterprise.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='enterprise.company')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('QUOTATION', 'Quotation'), ('PURCHASE_ORDER', 'Purchase Order'), ('DELIVERY_NOTE', 'Delivery Note'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('PAYMENT', 'Payment'), ('JOURNAL', 'Journal')], max_length=30)),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('reset_yearly', models.BooleanField(default=True)),
                ('last_reset_year', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_sequences', to='enterprise.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='enterprise.company')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='enterprise.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_branch_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_department_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'document_type'), name='unique_document_sequence'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_fiscal_year_per_company'),
        ),
    ]
