# Generated by Django 5.2.12 on 2026-07-29 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sequence', models.PositiveIntegerField()),
                ('required_permission', models.CharField(blank=True, default='', help_text='Optional Django permission codename required to approve this step.', max_length=150)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='enterprise.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to='enterprise.approvalstep')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='enterprise.approvalrequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='enterprise.approvalstep')),
            ],
            options={
                'ordering': ['action_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('PURCHASE_ORDER', 'Purchase Order'), ('SUPPLIER_INVOICE', 'Supplier Invoice'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('SALES_ORDER', 'Sales Order'), ('DELIVERY_NOTE', 'Delivery Note'), ('CUSTOMER_INVOICE', 'Customer Invoice'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('JOURNAL_ENTRY', 'Journal Entry')], max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='enterprise.company')),
            ],
            options={
                'ordering': ['company', 'document_type'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='enterprise.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='enterprise.approvalworkflow'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(fields=('company', 'document_type'), name='unique_approval_workflow_per_document_type'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_approval_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('workflow', 'content_type', 'object_id'), name='unique_pending_approval_request'),
        ),
    ]
