# Generated by Django 5.2.12 on 2026-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_currency_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt__isnull', False), models.Q(('mpesa_receipt', ''), _negated=True)), fields=('mpesa_receipt',), name='unique_nonblank_mpesa_receipt'),
        ),
    ]
