services:
  - type: web
    name: afriaxis-v7
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"

      - key: DJANGO_DEBUG
        value: "False"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: afriaxis-v7-db
          property: connectionString

databases:
  - name: afriaxis-v7-db
