# Generated by Django 5.2.12 on 2026-03-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
    ]
