# Generated by Django 5.2.12 on 2026-05-18 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_apartment_house_apartment_tenant_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
