# Generated by Django 5.2.12 on 2026-07-05 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rent_amount_paid_rent_balance_alter_rent_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='house',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='rentals.tenant'),
        ),
        migrations.AddField(
            model_name='rent',
            name='billing_month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
