# Generated by Django 5.2.12 on 2026-07-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rename_date_rent_created_at_house_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
