# Generated by Django 5.2.12 on 2026-08-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_approvalstep_approvalrequest_approvalaction_and_more'),
        ('rentals', '0006_rent_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='enterprise.company'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_apartment_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('apartment', 'house_number'), name='unique_house_number_per_apartment'),
        ),
    ]
