# Generated by Django 5.2.12 on 2026-08-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_apartment_company_tenant_active_alter_apartment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='acquisition_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='construction_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='construction_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='portfolio_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED', 'Mixed Use')], default='RESIDENTIAL', max_length=20),
        ),
    ]
