# Generated by Django 5.2.12 on 2026-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifipackage',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wifipackage',
            name='duration_days',
            field=models.IntegerField(default=0),
        ),
    ]
