# Generated by Django 5.2.12 on 2026-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_watermeter_waterreading_waterbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifipayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wifipayment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
