# Generated by Django 5.2.12 on 2026-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_created_at_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MD', 'Managing Director'), ('CEO', 'Chief Executive Officer'), ('GM', 'General Manager'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], max_length=20),
        ),
    ]
