# Generated by Django 5.2.12 on 2026-08-26 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_created_at_alter_userprofile_role'),
        ('enterprise', '0002_approvalstep_approvalrequest_approvalaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MD', 'Managing Director'), ('CEO', 'Chief Executive Officer'), ('GM', 'General Manager'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assignments', to='enterprise.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_assignments', to='enterprise.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assignments', to='enterprise.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_assignment')],
            },
        ),
    ]
