# Generated by Django 5.2.12 on 2026-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_companyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassignment',
            name='role',
            field=models.CharField(choices=[('MD', 'Managing Director'), ('CEO', 'Chief Executive Officer'), ('GM', 'General Manager'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('FINANCE', 'Finance'), ('AUDITOR', 'Auditor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MD', 'Managing Director'), ('CEO', 'Chief Executive Officer'), ('GM', 'General Manager'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('FINANCE', 'Finance'), ('AUDITOR', 'Auditor')], max_length=20),
        ),
    ]
