# Generated by Django 5.2.12 on 2026-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_companyassignment_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MD', 'Managing Director'), ('CEO', 'Chief Executive Officer'), ('GM', 'General Manager'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('FINANCE', 'Finance'), ('ACCOUNTS', 'Accounts'), ('AUDITOR', 'Auditor'), ('WIFI_TECHNICIAN', 'Wi-Fi Technician')], max_length=20),
        ),
    ]
