# Generated by Django 5.2.12 on 2026-06-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('money_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('money_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transaction_type', models.CharField(choices=[('money_in', 'Money In'), ('money_out', 'Money Out'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('suggested_category', models.CharField(choices=[('rent', 'Rent'), ('water', 'Water'), ('wifi', 'Wi-Fi'), ('rent_deposit', 'Rent Deposit'), ('water_deposit', 'Water Deposit'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('confidence', models.IntegerField(default=0)),
                ('match_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('statement_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.bankstatementupload')),
            ],
        ),
    ]
