# Generated by Django 5.2.12 on 2026-06-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('date_column', models.CharField(default='Date', max_length=100)),
                ('description_column', models.CharField(default='Description', max_length=100)),
                ('reference_column', models.CharField(default='Reference', max_length=100)),
                ('money_in_column', models.CharField(default='Money In', max_length=100)),
                ('money_out_column', models.CharField(default='Money Out', max_length=100)),
                ('balance_column', models.CharField(default='Balance', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
