# Generated by Django 5.2.12 on 2026-06-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bankstatementtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementupload',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.bankstatementtemplate'),
        ),
    ]
