# Generated by Django 5.2.12 on 2026-06-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bankstatementupload_template'),
        ('rentals', '0003_rent_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='notes',
            new_name='match_notes',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='auto_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.house'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.tenant'),
        ),
    ]
