# Generated by Django 5.2.12 on 2026-08-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_rename_notes_banktransaction_match_notes_and_more'),
        ('purchasing', '0004_alter_supplierpayment_payment_method'),
        ('sales', '0004_salesreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='matched_sales_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='sales.salesreceipt'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='purchasing.supplierpayment'),
        ),
    ]
