# Generated by Django 5.2.12 on 2026-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_banktransaction_matched_sales_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='suggested_category',
            field=models.CharField(choices=[('rent', 'Rent'), ('water', 'Water'), ('wifi', 'Wi-Fi'), ('rent_deposit', 'Rent Deposit'), ('water_deposit', 'Water Deposit'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('customer_receipt', 'Customer Receipt'), ('supplier_payment', 'Supplier Payment'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
