# Generated by Django 5.2.12 on 2026-08-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_banktransaction_suggested_category'),
        ('enterprise', '0002_approvalstep_approvalrequest_approvalaction_and_more'),
        ('rentals', '0006_rent_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='rentals.apartment'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='enterprise.company'),
        ),
        migrations.AlterField(
            model_name='bankstatementupload',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_uploads', to='banking.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='matched_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='rentals.house'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='matched_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='rentals.tenant'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='statement_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.bankstatementupload'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('company', 'account_number'), name='unique_bank_account_number_per_company'),
        ),
    ]
