# Generated by Django 5.2.12 on 2026-08-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_bankaccount_apartment_bankaccount_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='purpose',
            field=models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('WIFI', 'Wi-Fi'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
