# Generated by Django 5.2.12 on 2026-07-30 06:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_approvalstep_approvalrequest_approvalaction_and_more'),
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('sales', '0003_salesinvoice_salesinvoiceline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.billofmaterial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='enterprise.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('finished_goods_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output_orders', to='inventory.storagelocation')),
                ('raw_material_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_orders', to='inventory.storagelocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_lines', to='sales.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='manufacturing.productionorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='unique_production_order_per_company'),
        ),
        migrations.AddConstraint(
            model_name='productionordermaterial',
            constraint=models.UniqueConstraint(fields=('production_order', 'component'), name='unique_component_per_production_order'),
        ),
    ]
