# Generated by Django 5.2.12 on 2026-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='BANK', max_length=20),
        ),
    ]
