# Generated by Django 5.2.12 on 2026-07-28 22:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('billing', '0003_invoicepayment_unique_nonblank_mpesa_receipt'),
        ('enterprise', '0001_initial'),
        ('purchasing', '0002_supplierpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(max_length=60, unique=True)),
                ('note_type', models.CharField(choices=[('CUSTOMER_CREDIT', 'Customer Credit Note'), ('SUPPLIER_DEBIT', 'Supplier Debit Note')], max_length=30)),
                ('note_date', models.DateField()),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_notes', to='enterprise.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustment_notes', to=settings.AUTH_USER_MODEL)),
                ('customer_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_notes', to='billing.invoice')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_note', to='accounting.journalentry')),
                ('offset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_notes', to='accounting.account')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_adjustment_notes', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_notes', to='purchasing.supplier')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_notes', to='purchasing.supplierinvoice')),
            ],
            options={
                'ordering': ('-note_date', '-id'),
            },
        ),
    ]
