# Generated by Django 5.2.12 on 2026-07-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtimsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='AfriAxis Group', max_length=200)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=30)),
                ('branch_id', models.CharField(blank=True, default='00', max_length=20)),
                ('device_serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('client_id', models.CharField(blank=True, default='', max_length=200)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
