# Generated by Django 5.2.12 on 2026-08-16 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_rename_notes_banktransaction_match_notes_and_more'),
        ('sales', '0003_salesinvoice_salesinvoiceline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='BANK', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='sales.customer')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_receipts_posted', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.salesinvoice')),
            ],
        ),
    ]
